// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZLRlPmkYLpoAqjNR3mEQCfneGhlF_-I',
    appId: '1:299846056528:web:d0dc0c3416ff2d66ce2f55',
    messagingSenderId: '299846056528',
    projectId: 'medical-app-c8ed0',
    authDomain: 'medical-app-c8ed0.firebaseapp.com',
    storageBucket: 'medical-app-c8ed0.firebasestorage.app',
    measurementId: 'G-T5RWP5SH9J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkGJoWOSVNwSJmSnja7EJcrMIiZ-H7ZN4',
    appId: '1:299846056528:ios:c7e28f1f972161cace2f55',
    messagingSenderId: '299846056528',
    projectId: 'medical-app-c8ed0',
    storageBucket: 'medical-app-c8ed0.firebasestorage.app',
    iosBundleId: 'com.example.medicalapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkGJoWOSVNwSJmSnja7EJcrMIiZ-H7ZN4',
    appId: '1:299846056528:ios:c7e28f1f972161cace2f55',
    messagingSenderId: '299846056528',
    projectId: 'medical-app-c8ed0',
    storageBucket: 'medical-app-c8ed0.firebasestorage.app',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnZLRlPmkYLpoAqjNR3mEQCfneGhlF_-I',
    appId: '1:299846056528:web:fc03b01247f69674ce2f55',
    messagingSenderId: '299846056528',
    projectId: 'medical-app-c8ed0',
    authDomain: 'medical-app-c8ed0.firebaseapp.com',
    storageBucket: 'medical-app-c8ed0.firebasestorage.app',
    measurementId: 'G-TC752PTGT6',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw94cwMoevkVJgT_40ckZkKouoNt_pNEQ',
    appId: '1:299846056528:android:9ac14de4e5ad8318ce2f55',
    messagingSenderId: '299846056528',
    projectId: 'medical-app-c8ed0',
    storageBucket: 'medical-app-c8ed0.firebasestorage.app',
  );
}
